            // class persoon {
            //     id 2171,
            //     code 2170,
            //     rechtsTitel null,
            //     juridischNaam Neus,
            //     handelsVoornaam Ikenio,
            //     verkortGehuwdenaam null,
            //     typeIdentificatie null,
            //     idnummer FE 004134,
            //     oprGebdatum 529556400000,
            //     geslacht M,
            //     indGeldig J,
            //     status null,
            //     indPersoon J,
            //     sluitOverldatum null,
            //     indBlacklist N,
            //     indCheckBlacklist N,
            //     soundexVoornaam I250,
            //     soundexNaam N200,
            //     burgerlijkeStaat O,
            //     geboortePlaats Paramaribo,
            //     geboorteLand {
            //         laId 740,
            //         laOmschrijving Suriname,
            //         alpha2 SR,
            //         alpha3 SUR,
            //         nationaliteit Surinamer,
            //         indGeldig J,
            //         caption SUR - Suriname
            //     },
            //     nationaliteit {
            //         natId 224,
            //         natOmschrijving Surinamer,
            //         indGeldig J
            //     },
            //     adres Oleanderstraat 9,
            //     woonplaats Paramaribo,
            //     telefoon 8832540,
            //     email ikenio.neus@webhelp.com,
            //     defaultRekNr null,
            //     defaultBank null,
            //     caption 2171 - 2170 - Neus, Ikenio
            // },